### ISSUE TITLE
Make the analytics data public (or disable analytics)

### ISSUE THREAD

**Issue by lah7** [ClickWiki/clickwiki.net#4]
There is a Google Analytics set up for the wiki, but only a handful of people can access this. It'll be good if  this data can be public for everyone to see.

**Comment by robinkooli** [comment]
Is Google Analytics even needed anymore? I don't see any usage it for especially that site is now hosted on Github. Also for paranoid people Google Analytics data collection isn't best thing.

**Comment by lah7** [comment]
Analytics definitely helps to identify what the wiki content is most used, as well as providing technical insight to the sort of browsers our visitors use.

With the new GDPR law coming in on May 25, a revised privacy policy will be needed if we continue with Analytics, so you might be right that analytics isn't a necessity. At least without analytics, we won't be collecting data from visitors of any kind. :thinking:

**Comment by robinkooli** [comment]
Is there any better alternative? https://matomo.org/ self-hosted one?

**Comment by lah7** [comment]
Thanks for the suggestion. I've used Piwik a long, long time ago, but it'll need a web server to run on. ClickWiki is going "serverless" (hence the move to GitHub Pages) so we'll need a free cloud/API driven one, or no analytics.

**Comment by robinkooli** [comment]
Good compromise would be to have script to opt-in/opt-out from analytics, that adds cookie and javascript magic then does the analytics part.
