### ISSUE TITLE
Images fractionally "cut off" in menus

### ISSUE THREAD

**Issue by lah7** [ClickWiki/clickwiki.net#9]
Spotted by @advaith1, some images in menus are cut off by a few pixels.

**Comment by advaith1** [comment]
![Screenshot 1](https://cdn.discordapp.com/attachments/317095824754606080/447159201429717002/Screen_Shot_2018-05-18_at_3.10.53_PM.png) ![Screenshot 2](https://cdn.discordapp.com/attachments/317095824754606080/447159347626377216/Screen_Shot_2018-05-18_at_3.11.29_PM.png) ![Screenshot 3](https://cdn.discordapp.com/attachments/317095824754606080/447159350260137995/Screen_Shot_2018-05-18_at_3.11.21_PM.png)
